#pragma once

enum potion_type
{
    POT_CURING,
    POT_HEAL_WOUNDS,
    POT_HASTE,
    POT_MIGHT,
    POT_BRILLIANCE,
    POT_STABBING,
    POT_FLIGHT,
    POT_CANCELLATION,
    POT_AMBROSIA,
    POT_INVISIBILITY,
    POT_DEGENERATION,
    POT_EXPERIENCE,
    POT_MAGIC,
    POT_BERSERK_RAGE,
    POT_MUTATION,
    POT_RESISTANCE,
    POT_LIGNIFY,
    POT_DIVINE_FAVOUR,
    POT_PENANCE,
    NUM_POTIONS
};

// used for objstat
const vector<potion_type> potion_types =
{
    POT_CURING,
    POT_HEAL_WOUNDS,
    POT_HASTE,
    POT_MIGHT,
    POT_BRILLIANCE,
    POT_STABBING,
    POT_FLIGHT,
    POT_CANCELLATION,
    POT_AMBROSIA,
    POT_INVISIBILITY,
    POT_DEGENERATION,
    POT_EXPERIENCE,
    POT_MAGIC,
    POT_BERSERK_RAGE,
    POT_MUTATION,
    POT_RESISTANCE,
    POT_LIGNIFY,
    POT_DIVINE_FAVOUR,
    POT_PENANCE,
};

#define CASE_REMOVED_POTIONS(pot)
